### PR TITLE
Update gradle to prepare workspace for Ganache

### PR DESCRIPTION
**Pull request by rogersanick**

### CODE REVIEW

**Comment by peterli-r3** [comment]
During my playing around this a couple weeks ago, I also found that we can have a customized RunConfig for better Corda<>ganache experience. check here: https://github.com/corda/samples/blob/ganacheConfig/yo-cordapp/.idea/runConfigurations/ganacheBuild.xml

**Comment by rogersanick** [comment]
@peterli-r3 , added run configs to trigger the ganache build. Let me know what you think. If you're happy with the changes feel free to approve.

**Comment by rogersanick** [comment]
Also here as well: https://github.com/corda/cordapp-template-kotlin/pull/74

**Review by peterli-r3 — APPROVED** [review]
Everything looks good. Mr.Rogers. @rogersanick

**Pull request merged**
